# Generated by Django 5.2.7 on 2025-10-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_user_created_on_user_updated_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                ],
                default="employee",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
