# Generated by Django 5.2.7 on 2025-10-18 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_verification_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
