# Generated by Django 5.2.7 on 2025-10-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='attributes'),
        ),
    ]
