# Generated by Django 5.2.7 on 2025-10-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="attributes"),
        ),
    ]
