# Generated by Django 5.2.7 on 2025-10-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='attributes')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=11, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('personal_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_married', models.BooleanField(default=False)),
                ('number_of_children', models.PositiveSmallIntegerField(default=0)),
                ('graduation', models.CharField(blank=True, max_length=255, null=True)),
                ('mandatory_military_service_completed', models.BooleanField(default=False)),
                ('driver_license', models.CharField(blank=True, max_length=20, null=True)),
                ('disability_degree', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('second_emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payroll_bank_account_no', models.CharField(blank=True, max_length=34, null=True)),
                ('payroll_bank_account_iban', models.CharField(blank=True, max_length=34, null=True)),
                ('payroll_bank_account_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'personal detail',
                'verbose_name_plural': 'personal details',
            },
        ),
    ]
