# Generated by Django 5.2.7 on 2025-10-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_personaldetail_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
