# Generated by Django 5.2.7 on 2025-10-25 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("titles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="tenant",
        ),
    ]
